### ISSUE TITLE
Bunny's roadmap

### ISSUE THREAD

**Issue by amsryq** [pyoncord/Bunny#1]
### Pretty much done
- [x] Tabs UI for Vendetta's core component
- [x] Reload less theme changing
- [x] Improvement of Vendetta plugins/themes installation experience
- [x] Rename Pyondetta -> Bunny
- [x] Our very own mod loader, [PyoncordXposed](https://github.com/pyoncord/pyonxposed) for Android and [PyoncordTweak](https://github.com/pyoncord/PyoncordTweak) for iOS
- [x] Implement translation (support multiple languages)
- [x] Support React DevTools from JS side
- [x] Support custom fonts 
- [x] Implement Metro caches, allowing Bunny to start up 2-4x faster (from my testing) than Vendetta/in its current state

### Working on (not in order)
- [ ] Bunny's own API, Vendetta's as legacy
  - Vendetta API will stay as `window.vendetta` without any extensions, and Bunny will have its own API at `window.bunny`
  - Bunny plugins will have access to Bunny's API, and using Vendetta's API is not recommended
- [ ] New theming standards and ecosystem
	- [ ] Custom icons support, built in!*
	- [ ] Interchange of themes based on the system's theme
- [ ] Bunny's plugin ecosystem
	- Repository, template, plugin checking, this should be in a separate issue
	- Offer easy migration from legacy (Vendetta) to modern (Bunny) plugins, whenever anyone would like to port and maintain an existing VD plugin
- [ ] Improve error handling
	- [ ] Users are provided with more control over errors they are facing besides safe mode
	- [ ] Implement patches that give more hints behind the cause of a soft crash
	- [x] Plugin's errors to be visible in the UI for clarity that the plugin is broken

*Native side (loader) changes are required; this means this feature will likely be missing in iOS until someone wishes to contribute

**Comment by mucookul** [comment]
Cool, came here from sunset shutting down

Also I can help with ios

**Comment by tye-exe** [comment]
I'm not very familiar with type script or JavaScript, but I'll happily act as a tester for Android!

Also, you might want to consider getting into contact with Vencord, as they have a [link ](https://vencord.dev/faq/#Is-there-a-mobile-version-of-Vencord?) that points to the original read-only repository for Vendetta.

Edit: Although I do have experience working in Java projects & as far as I'm aware, android supports Java applications, but I don't really know much about it.

**Comment by amsryq** [comment]
Thank you for the suggestions, but I want to hold on advertising until Bunny has a proper installation method and we would need our own loader for that. Currently, I'm still working on the Xposed module so yeah

**Comment by frostproto27** [comment]
interested to see where this goes, sad that vendetta is EOL as there aren't any other up to date alternatives. maybe this could be one in the future when it's more complete
also, the classic discord ui (instead of tabsv2) being easily accessible would be nice if thats planned.

**Comment by lustfulglance** [comment]
i am very interested on how this goes, good luck my guy

**Comment by Dawimpy** [comment]
*looks like i need to learn ts for real now
